= Create new LRA programmatic client API
:author:            Marco Sappe' Griot
:email:             msappegr@redhat.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Overview
Create new LRA programmatic client API to replace the deprecated NarayanaLRAClient. The current LRA client implementation was deprecated and moved to an internal package, leaving users without a proper public API for programmatically interacting with LRA coordinators. This proposal introduces a new client implementation based on the MicroProfile REST Client specification that provides all the functionality of the deprecated client while following modern standards and best practices. The new client will support multiple coordinator instances using the Stork library for load balancing and will serve as the recommended way for applications to interact with LRA coordinators programmatically. 
== Issue Metadata

=== Issue

* https://github.com/jbosstm/lra/issues/113

=== Related Issues

* https://github.com/jbosstm/lra/issues/175
* https://github.com/jbosstm/lra/issues/157

=== Dev Contacts

* mailto:msappegr@redhat.com[Marco Sappe' Griot]

=== Affected Projects or Components
* https://github.com/jbosstm/lra/

=== Other Interested Projects
* Quarkus and WildFly

== Requirements

=== Hard Requirements

* Implement a new LRA client API using the RESTEasy implementation of the MicroProfile REST Client 
* Provide access to all LRA Coordinator endpoints (start, join, leave, close, cancel, status)
* Support multiple coordinator instances using Stork library for load balancing
* Replace all functionality currently provided by the deprecated NarayanaLRAClient
* Maintain backward compatibility for applications during migration period
* Include comprehensive unit tests for all client functionality
* Include integration tests with actual LRA coordinator instances
* The client must be `closable` or `auto-closeable` as agreed in the issue #157

=== Nice-to-Have Requirements

* Provide migration utilities or documentation to ease transition from NarayanaLRAClient
* Support for configuration via MicroProfile Config
* Async/reactive client variants for better performance in non-blocking environments
* Provide unit and integration tests.

=== Non-Requirements

* This proposal does not aim to change the LRA Coordinator implementation
* No changes to the LRA specification or protocol are required
* No modifications to existing JAX-RS annotations or CDI integration

== Backwards Compatibility

* Having a new client might affect applications using the internal NarayanaLRAClient, though the actual client is internal so just announcing the changes and releasing it as a minor release should be enough. 

== Security Considerations
* Implement the client in a way it can be configured to use SSL or KeyStore using the RestClientBuilder methods https://download.eclipse.org/microprofile/microprofile-rest-client-1.3/apidocs/org/eclipse/microprofile/rest/client/RestClientBuilder.html 

== Test Plan
- Add unit test and integration tests (with the use of the Coordinator). 
- Integration tests will be implemented with failsafe plugin and included under lra-test module. The WildFly Coordinator will be used for this purpose.

== Community Documentation

- Implementation details will be added here:  https://github.com/jbosstm/narayana/blob/main/docs/src/main/asciidoc/project/lra/jaxrs.adoc

== Release Note Content
- Removal of internal NarayanaLRAClient. Please use the new programmatic client instead.
