= Add support for JEP 444: Virtual Threads and JEP 238: Multi-Release JAR Files
:author:            Michael Musgrove
:email:             mmusgrov@ibm.com
:toc:               left
:icons:             font
:idprefix:
:idseparator:       -

== Requirements

A version of BasicAction.java will be created that uses *Executors.newVirtualThreadPerTaskExecutor* instead of *Executors.newFixedThreadPool*.

A test will be created that sets the properties that control asynchronous operations as defined in the [CoordinatorEnvironmentBean](https://github.com/jbosstm/narayana/blob/7.3.3.Final/ArjunaCore/arjuna/classes/com/arjuna/ats/arjuna/common/CoordinatorEnvironmentBean.java) and will run a transaction with three enlisted resources. Three is chosen since the last resource runs on the callers thread so the test should verify that the first two run on virtual threads - we choose to enlist three resources to verify that the implementation can create more than one virtual thread.

The maven pom will be changed to run two executions of the compiler plugin (to detect when release 21 is in use) in order to produce a Multi-Release JAR. This will be achieved through the use of a profile and the profile will configure the compiler plugin to choose the appropriate sources which will be added to a different part of the source tree (since the new features would not compile on earlier versions of the jdk). The test will only run when the new profile is active.

=== Hard Requirements

All of the above.

=== Nice-to-Have Requirements

Future uses of the JEP 238: Multi-Release JAR Files feature will be to experiment with JEP 505: Structured Concurrency (Fifth Preview).

